"""url file size

Revision ID: 86a2d08cfade
Revises: c8d3d789bd34
Create Date: 2022-04-04 04:16:03.267866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a2d08cfade'
down_revision = 'c8d3d789bd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'size')
    # ### end Alembic commands ###
